#!/usr/bin/python3
#
# Usage
# ~~~~~
# python ./monitor.py
# python ./aggregator.py
#
# sqlite3 resource_usage.db
# sqlite> .help
# sqlite> .tables
# sqlite> select * from cpu_usage;
# sqlite> .quit

import click
import json
import queue
import time
import utilities

connection = None  # TODO: Fix this !
resource_queue = queue.Queue()
no_of_cpus = 4

def on_message(client, userdata, message):
    topic = message.topic
    payload = str(message.payload.decode("utf-8"))
    print(f"Received {topic}: {payload}")
    cpu_usage = json.loads(payload)
    # cpu_arch = json.load(payload)
    # cpu_count = cpu_arch["count"]
    busy_percent = cpu_usage["busy_percent"]
    busy_total = sum(busy_percent)
    resource_queue.put(busy_total)


def generate_current_time():
    unix_time = time.time()
    utilities.write_time(connection, unix_time)
    print("Time written into db: {unix_time}")


def initialize(host, topic_subscribe):
    configuration = {
        "mqtt": {
            "host": host,
            "on_message": on_message,
            "topic_subscribe": topic_subscribe,
        }
    }
    utilities.initialize_mqtt(configuration["mqtt"])
    return configuration


@click.group()
def main():
    pass


@main.command(help="Create aggregator")
@click.option("--host", "-h", default="localhost")
@click.option("--topic_subscribe", "-t", default="cpu_usage/#")
def create(host, topic_subscribe):
    """
    Create a new aggregator.

    Parameters:
    host (str): The hostname or IP address of the MQTT broker to connect to.
    topic_subscribe (str): The topic to subscribe to.

    Returns:
    None

    Raises:
    ConnectionError: If the client cannot connect to the MQTT broker.
    """

    global connection  # TODO: Fix this !
    configuration = initialize(host, topic_subscribe)
    connection = utilities.initialize_database()
    # utilities.write_record(connection, )
    try:
        while True:
            busy_total = resource_queue.get() / no_of_cpus
            generate_current_time()
            utilities.write_record(connection, busy_total)
            print(f"Database write: {busy_total}")
    except KeyboardInterrupt:
        utilities.close_database(connection)
        print("Database closed")

@main.command(help="Resets everything")
def reset():
    print("Resetting database")
    utilities.reset_database()
    utilities.create_database_tables(connection)  # once only
    print("Resetting MQTT messages") 
    # TODO Reset Exit
    utilities.reset_MQTT_retained()

if __name__ == "__main__":
    main()
